'use strict';

const { deepClone } = require('./normalize');

// Fields that must never be sent to the destination create endpoint because
// they are generated by / belong to the source portal. Per the live
// HubSpotFormDefinitionCreateRequest schema, `id` is the only field excluded
// from the create request shape (createdAt/updatedAt/archived/etc. are all
// part of the create schema and are preserved as-is).
const FIELDS_TO_STRIP = ['id', 'guid', 'portalId'];

// Known cases where a value that is technically present and valid JSON is
// still meaningless (or actively wrong) once copied to a different portal,
// because it references an ID space that is local to the source portal.
// These are never silently dropped - they are preserved in the payload
// (since removing them could be seen as silently discarding configuration)
// but flagged so a human can verify/correct them after migration.
const PORTABILITY_RISK_CHECKS = [
  {
    check: (form) => Array.isArray(form?.configuration?.notifyRecipients) && form.configuration.notifyRecipients.length > 0,
    message:
      'configuration.notifyRecipients contains source-portal user IDs. HubSpot user IDs are not shared across portals, so these recipients will very likely not resolve to a valid user in the destination portal. Verify/update notification recipients manually after migration.',
  },
  {
    check: (form) =>
      form?.legalConsentOptions &&
      Array.isArray(form.legalConsentOptions.subscriptionTypeIds) &&
      form.legalConsentOptions.subscriptionTypeIds.length > 0,
    message:
      'legalConsentOptions.subscriptionTypeIds references source-portal subscription type IDs. Subscription types are portal-specific; confirm the destination portal has matching subscription types with the same IDs, or update this configuration manually.',
  },
  {
    check: (form) => Array.isArray(form?.configuration?.lifecycleStages) && form.configuration.lifecycleStages.length > 0,
    message:
      'configuration.lifecycleStages is populated. If any of these reference custom (non-default) lifecycle stages, verify the destination portal has equivalent stages defined.',
  },
];

function collectPortabilityWarnings(sourceForm) {
  const warnings = [];
  for (const { check, message } of PORTABILITY_RISK_CHECKS) {
    if (check(sourceForm)) warnings.push(message);
  }
  return warnings;
}

/**
 * Builds the POST /marketing/v3/forms payload from a full source form
 * definition. Strips only portal-generated identifiers; everything else
 * (configuration, displayOptions, fieldGroups, legalConsentOptions, etc.) is
 * preserved verbatim so the destination form matches the source as closely
 * as the API allows. Returns any portability warnings that should be logged
 * (not silently dropped) alongside the payload.
 */
function buildCreatePayload(sourceForm, { destinationName } = {}) {
  const payload = deepClone(sourceForm);
  for (const field of FIELDS_TO_STRIP) {
    delete payload[field];
  }
  if (destinationName) payload.name = destinationName;

  return { payload, warnings: collectPortabilityWarnings(sourceForm) };
}

// The only fields the PATCH /marketing/v3/forms/{formId} endpoint accepts,
// per the live HubSpotFormDefinitionPatchRequest schema. formType, id,
// createdAt and updatedAt are deliberately excluded - they aren't part of
// that schema and formType isn't patchable at all.
const PATCHABLE_FIELDS = ['archived', 'configuration', 'displayOptions', 'fieldGroups', 'legalConsentOptions'];

/**
 * Builds a PATCH payload that brings an already-existing destination form
 * back in sync with the current source definition - used when a source form
 * changed after its destination counterpart was created. Only ever includes
 * fields the PATCH endpoint actually accepts.
 */
function buildUpdatePayload(sourceForm, { destinationName } = {}) {
  const payload = {};
  for (const field of PATCHABLE_FIELDS) {
    payload[field] = deepClone(sourceForm[field]);
  }
  payload.name = destinationName || sourceForm.name;

  return { payload, warnings: collectPortabilityWarnings(sourceForm) };
}

module.exports = { buildCreatePayload, buildUpdatePayload };
